---
root: true
# parser: babel-eslint
env:
  browser: true
  node: true
  commonjs: true
  es6: true
globals:
  process: true
parserOptions:
  ecmaVersion: 2017
  sourceType: module
rules:
  strict:
  - 2
  - global
  linebreak-style: 2
  no-unused-expressions:
  - 2
  - allowShortCircuit: true
  no-multi-str: 2
  no-bitwise: 2
  eqeqeq:
  - 2
  - always
  - null: ignore
  guard-for-in: 2
  no-undef: 2
  no-unused-vars:
  - 2
  - args: none
  no-use-before-define: 0
  curly:
  - 2
  - multi-line
  operator-linebreak:
  - 2
  - after
  - overrides:
      "?": before
      "=": before
      "-": before
      "/": before
      "*": before
      "==": before
      "===": before
      "!=": before
      "!==": before
      ">": before
      ">=": before
      "<": before
      "<=": before
      ":": ignore
      "&&": ignore
      "||": ignore
  max-len:
  - 2
  - 130
  indent:
  - 2
  - 2
  - MemberExpression: off
    ignoredNodes:
    - ConditionalExpression
    - SwitchCase
  quotes:
  - 2
  - single
  no-mixed-spaces-and-tabs: 2
  no-trailing-spaces: 2
  space-unary-ops:
  - 2
  - nonwords: false
    overrides: {}
  one-var:
  - 2
  - never
  brace-style:
  - 2
  - 1tbs
  - allowSingleLine: true
  keyword-spacing:
  - 2
  - after: false
    overrides:
      if:
        after: true
      else:
        after: true
      for:
        after: true
      while:
        after: true
      do:
        after: true
      switch:
        after: true
      return:
        after: true
      try:
        after: true
      case:
        after: true
      throw:
        after: true
      var:
        after: true
      let:
        after: true
      import:
        after: true
      from:
        after: true
      const:
        after: true
  space-infix-ops: 2
  space-before-blocks:
  - 2
  - always
  eol-last: 2
  space-before-function-paren:
  - 2
  - anonymous: ignore
    named: never
  array-bracket-spacing:
  - 2
  - never
  space-in-parens:
  - 2
  - never
  no-with: 2
  no-spaced-func: 2
  key-spacing:
  - 2
  - mode: minimum
  dot-notation: 2
  semi:
  - 2
  - always
  semi-spacing:
  - 2
  - before: false
    after: true
  yoda:
  - 2
  - never
  spaced-comment:
  - 2
  - always
  lines-around-comment:
  - 2
  - allowArrayStart: true
    allowBlockStart: true
    allowObjectStart: true
